# Theme configurations for Next.
theme_config:
  footer:
    powered: true
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: fa fa-heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#ff0000"